### ISSUE TITLE
Exception during creation

### ISSUE THREAD

**Issue by TomberWolf** [MrTrollNugNug/Rope-Bridge#7]
Thermos 1.7.10:

[18:20:28] [Server thread/ERROR]: A TileEntity ropebridge_tile_entity(com.czechmate777.ropebridge.tileentity.ModTileEntity) located @ 1713,72,1433 has thrown an exception during creation, it cannot be created. Report this to the mod author
java.lang.InstantiationException: com.czechmate777.ropebridge.tileentity.ModTileEntity
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.tileentity.TileEntity.func_145827_c(TileEntity.java:116) [aor.class:?]
	at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:525) [aqk.class:?]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:44) [ChunkIOProvider.class:1.7.10-1614.58]
	at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:15) [ChunkIOProvider.class:1.7.10-1614.58]
	at net.minecraftforge.common.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:189) [AsynchronousExecutor$Task.class:1.7.10-1614.58]
	at net.minecraftforge.common.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:354) [AsynchronousExecutor.class:1.7.10-1614.58]
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:30) [ChunkIOExecutor.class:1.7.10-1614.58]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:917) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodException: com.czechmate777.ropebridge.tileentity.ModTileEntity.<init>()
	at java.lang.Class.getConstructor0(Unknown Source) ~[?:1.8.0_121]
	... 13 more

**Comment by Cazsius** [comment]
1.7.10 version is no longer supported. I apologize.
